//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ClientID { get; set; }
        public string TourName { get; set; }
        public System.DateTime eventDate { get; set; }
        public decimal Payment { get; set; }
        public System.DateTime dateBooked { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
