//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourEvent
    {
        public string TourName { get; set; }
        public System.DateTime eventDate { get; set; }
        public decimal eventFee { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
